FROM rust:1.82-bookworm AS builder

WORKDIR /opt/hyperdisk
COPY server/ ./server/
WORKDIR /opt/hyperdisk/server
RUN cargo build --release -p hd-metadata-center -p hd-update-service -p hd-dna-service -p hd-api-gateway

FROM debian:bookworm-slim
COPY --from=builder /opt/hyperdisk/server/target/release/hd-metadata-center /usr/local/bin/
COPY --from=builder /opt/hyperdisk/server/target/release/hd-update-service /usr/local/bin/
COPY --from=builder /opt/hyperdisk/server/target/release/hd-dna-service /usr/local/bin/
COPY --from=builder /opt/hyperdisk/server/target/release/hd-api-gateway /usr/local/bin/

CMD ["hd-metadata-center"]
