set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)

set(WDK_ROOT "C:/Program Files (x86)/Windows Kits/10" CACHE PATH "WDK root")
set(WDK_VERSION "10.0.26100.0" CACHE STRING "WDK version")
set(WDK_BIN_ROOT "${WDK_ROOT}/bin/${WDK_VERSION}/x64")
set(WDK_INC_ROOT "${WDK_ROOT}/Include/${WDK_VERSION}")
set(WDK_LIB_ROOT "${WDK_ROOT}/Lib/${WDK_VERSION}")

set(CMAKE_C_COMPILER "${WDK_BIN_ROOT}/cl.exe" CACHE FILEPATH "C compiler")
set(CMAKE_C_LINKER "${WDK_BIN_ROOT}/link.exe" CACHE FILEPATH "Linker")
set(CMAKE_LIB_LINKER "${WDK_BIN_ROOT}/lib.exe" CACHE FILEPATH "Lib linker")
set(CMAKE_AR "${WDK_BIN_ROOT}/lib.exe" CACHE FILEPATH "Archiver")

set(CMAKE_C_FLAGS_INIT "/kernel /GS- /GL- /MP /W4 /WX- /Zi /Od /Oi /Oy- /D _WIN32 /D _AMD64_ /D _KERNEL_MODE /D WIN32_LEAN_AND_MEAN=1 /D _NO_CRT_STDIO_EQUAL /D NTDDI_VERSION=NTDDI_WIN10_CO /D WINVER=0x0A00 /D _WIN32_WINNT=0x0A00 /I\"${WDK_INC_ROOT}/km\" /I\"${WDK_INC_ROOT}/shared\" /I\"${WDK_INC_ROOT}/ucrt\" /I\"${WDK_INC_ROOT}/km/crt\"")

set(CMAKE_SHARED_LINKER_FLAGS_INIT "/NODEFAULTLIB /SUBSYSTEM:NATIVE /DRIVER /KERNEL /ENTRY:DriverEntry /MERGE:.text=.PAGE /MERGE:.data=.PAGE /SECTION:INIT,d /SECTION:PAGE,d /IGNORE:4197 /IGNORE:4010 /IGNORE:4078 /IGNORE:4221 /LIBPATH:\"${WDK_LIB_ROOT}/km/x64\"")
